// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataHandler.Models
{
    public partial class ConnectionType
    {
        public ConnectionType()
        {
            ConnectionCapability = new HashSet<ConnectionCapability>();
        }

        [Key]
        public int ConnectionTypeId { get; set; }
        [Required]
        public string Connection { get; set; }

        [InverseProperty("ConnectionType")]
        public virtual ICollection<ConnectionCapability> ConnectionCapability { get; set; }
    }
}