// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataHandler.Models
{
    public partial class Device
    {
        public Device()
        {
            ConnectionCapability = new HashSet<ConnectionCapability>();
            Service = new HashSet<Service>();
        }

        [Key]
        public int DeviceId { get; set; }
        [Required]
        public string Name { get; set; }
        [Column("ID")]
        public Guid Id { get; set; }
        public string Archetype { get; set; }
        public bool? Certified { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelId { get; set; }
        public string ProductArchetype { get; set; }
        public string ProductName { get; set; }
        public string SoftwareVersion { get; set; }
        public int DeviceTypeId { get; set; }
        public int ProductFamilyId { get; set; }
        [Column(TypeName = "xml")]
        public string ProductProperties { get; set; }

        [ForeignKey("DeviceTypeId")]
        [InverseProperty("Device")]
        public virtual DeviceType DeviceType { get; set; }
        [ForeignKey("ProductFamilyId")]
        [InverseProperty("Device")]
        public virtual ProductFamily ProductFamily { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<ConnectionCapability> ConnectionCapability { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<Service> Service { get; set; }
    }
}