// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataHandler.Models
{
    public partial class DeviceType
    {
        public DeviceType()
        {
            Device = new HashSet<Device>();
        }

        [Key]
        public int DeviceTypeId { get; set; }
        public string DeviceTypeName { get; set; }

        [InverseProperty("DeviceType")]
        public virtual ICollection<Device> Device { get; set; }
    }
}