// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataHandler.Models
{
    public partial class Service
    {
        [Key]
        public int ServiceId { get; set; }
        [Column("ID")]
        public Guid Id { get; set; }
        [Required]
        public string ServiceName { get; set; }
        public int ServiceTypeId { get; set; }
        public int DeviceId { get; set; }

        [ForeignKey("DeviceId")]
        [InverseProperty("Service")]
        public virtual Device Device { get; set; }
        [ForeignKey("ServiceTypeId")]
        [InverseProperty("Service")]
        public virtual ServiceType ServiceType { get; set; }
    }
}