// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataHandler.Models
{
    public partial class ServiceType
    {
        public ServiceType()
        {
            Service = new HashSet<Service>();
        }

        [Key]
        public int ServiceTypeId { get; set; }
        [Required]
        public string ServiceName { get; set; }

        [InverseProperty("ServiceType")]
        public virtual ICollection<Service> Service { get; set; }
    }
}